apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::158724841371:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-qlcycLkioJrm
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::158724841371:user/sanjay
      username: sanjay
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 87c8deea-283a-4958-97d5-b3456be45739